@extends('client-portal.layout')

@section('title', 'Tiket')

@section('content')
<div class="space-y-6"><div class="flex justify-between"><div><h1 class="text-2xl font-bold text-gray-900">Tiket</h1><p class="text-sm text-gray-500 mt-1">Daftar tiket support Anda</p></div><a href="{{ route('client.tickets.create') }}" class="inline-flex items-center gap-2 px-4 py-2.5 bg-blue-600 text-white text-sm font-semibold rounded-lg hover:bg-blue-700 transition"><svg xmlns="http://www.w3.org/2000/svg" class="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M12 4v16m8-8H4"/></svg>Buat Tiket</a></div>
<div class="bg-white rounded-xl border border-gray-100 shadow-sm overflow-hidden"><div class="overflow-x-auto"><table class="w-full text-sm"><thead><tr class="bg-gray-50 text-left"><th class="px-4 py-3 text-xs font-semibold text-gray-400 uppercase">#</th><th class="px-4 py-3 text-xs font-semibold text-gray-400 uppercase">Subjek</th><th class="px-4 py-3 text-xs font-semibold text-gray-400 uppercase">Kategori</th><th class="px-4 py-3 text-xs font-semibold text-gray-400 uppercase">Prioritas</th><th class="px-4 py-3 text-xs font-semibold text-gray-400 uppercase">Status</th><th class="px-4 py-3 text-xs font-semibold text-gray-400 uppercase text-center">Detail</th></tr></thead><tbody class="divide-y divide-gray-100">
@forelse($tickets as $t) @php $pc=['low'=>'bg-blue-100 text-blue-700','medium'=>'bg-amber-100 text-amber-700','high'=>'bg-red-100 text-red-700','urgent'=>'bg-red-200 text-red-800']; $sc=['open'=>'bg-blue-100 text-blue-700','in_progress'=>'bg-amber-100 text-amber-700','resolved'=>'bg-emerald-100 text-emerald-700','closed'=>'bg-gray-100 text-gray-700']; @endphp
<tr class="hover:bg-gray-50"><td class="px-4 py-3 font-mono text-xs">{{ $t->ticket_number }}</td><td class="px-4 py-3 font-medium">{{ $t->subject }}</td><td class="px-4 py-3 text-gray-600">{{ $t->category?->name ?? '-' }}</td><td class="px-4 py-3"><span class="inline-flex px-2 py-0.5 rounded text-[10px] font-semibold {{ $pc[$t->priority] ?? '' }}">{{ strtoupper($t->priority) }}</span></td><td class="px-4 py-3"><span class="inline-flex px-2 py-0.5 rounded-full text-xs font-semibold {{ $sc[$t->status] ?? '' }}">{{ strtoupper(str_replace('_',' ',$t->status)) }}</span></td><td class="px-4 py-3 text-center"><a href="{{ route('client.tickets.show', $t->id) }}" class="text-blue-600 text-xs">Detail</a></td></tr>
@empty <tr><td colspan="6" class="px-6 py-10 text-center text-gray-400">Belum ada tiket.</td></tr> @endforelse
</tbody></table></div>@if($tickets->hasPages())<div class="px-6 py-3 border-t">{{ $tickets->links() }}</div>@endif</div></div>
@endsection
